version: "3"
services:

  nestjs:
    build:
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./web-app/.env
    ports:
      - 3000:3000
    volumes:
      - ./web-app/:/usr/web-app/

  postgres:
    env_file:
      - ./.docker/db/.env.db.dev

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    env_file:
      - ./.docker/pgadmin/.env.dev.pgadmin
    ports:
      - 8080:80
    depends_on:
      - postgres

  expo:
    container_name: expo
    build:
      context: ./mobile-app/
      dockerfile: ./Dockerfile.dev
    ports:
      - 19000:19000
      - 19006:19006
      - 19001:19001
      - 19002:19002
    volumes:
      - ./mobile-app/:/usr/mobile-app/
