name: Deploy on aws EB
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging AWS
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      working-directory: ./web-app
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      working-directory: ./web-app
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "Hex docker"
        environment_name: Hexdocker-env
        version_label: ver-${{ github.sha }}
        region: us-east-1
        deployment_package: deploy.zip